### ISSUE TITLE
Platform support?

### ISSUE THREAD

**Issue by tmm1** [shurcooL/trayhost#16]
The readme says linux and windows aren't supported, but I see recent commits that seem to indicate otherwise?

**Comment by shurcooL** [comment]
Which recent commits are you referring to?

I have not tested `trayhost` on Linux or Windows in a very long time. It might be close to working, or it might require some updates for API changes.

https://github.com/shurcooL/trayhost#platform-support is accurate, albeit overly pessimistic about the status of Windows and Linux. But I don't want to say supported unless they're 100% supported, and for that I'd need someone who uses that platform to own it.

**Comment by tmm1** [comment]
Okay understood, thanks. I had seen a commit from 10/2016 (https://github.com/shurcooL/trayhost/commits/master/platform/windows/tray.c) which wasn't in some of the other forks.

**Comment by shurcooL** [comment]
Yeah, some PRs like #3 and #13 did work to help Linux/Windows, but I don't think it's enough to claim supported status.

**Comment by shurcooL** [comment]
@tmm1, do you think it'd be better if I changed it from "Not implemented" to "Partially implemented but not supported"?

**Comment by tmm1** [comment]
Yes, that would certainly be more accurate.

FWIW the windows code in this fork has some minor build failures but works quite well.

**Comment by shurcooL** [comment]
Thanks, I'll do that.
