### ISSUE TITLE
does not compile when cgo is disabled

### ISSUE THREAD

**Issue by 0xfederama** [shurcooL/trayhost#22]
I get these error when I try to build for darwin, while when I build for linux everything is ok
![Screenshot from 2020-06-05 11-51-43](https://user-images.githubusercontent.com/45485339/83864274-cc82b200-a724-11ea-9e7a-63a7ab4c94f4.png)

**Comment by dmitshur** [comment]
It looks like you’re trying to cross-compile, and not explicitly enabling cgo.

From https://golang.org/cmd/cgo/:

> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling. You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it.
